export const MOOD_CONFIGS = {
  grateful: { 
    emoji: '🙏', 
    color: 'from-emerald-400 to-teal-500',
    label: 'Grateful'
  },
  peaceful: { 
    emoji: '🕊️', 
    color: 'from-blue-400 to-cyan-500',
    label: 'Peaceful'
  },
  excited: { 
    emoji: '🎉', 
    color: 'from-yellow-400 to-orange-500',
    label: 'Excited'
  },
  hopeful: { 
    emoji: '🌅', 
    color: 'from-pink-400 to-purple-500',
    label: 'Hopeful'
  },
  reflective: { 
    emoji: '🤔', 
    color: 'from-indigo-400 to-purple-500',
    label: 'Reflective'
  },
  anxious: { 
    emoji: '😰', 
    color: 'from-red-400 to-pink-500',
    label: 'Anxious'
  },
  sad: { 
    emoji: '😢', 
    color: 'from-blue-500 to-indigo-600',
    label: 'Sad'
  },
  angry: { 
    emoji: '😠', 
    color: 'from-red-500 to-red-600',
    label: 'Angry'
  },
  confused: { 
    emoji: '😵', 
    color: 'from-gray-400 to-gray-500',
    label: 'Confused'
  },
  lonely: { 
    emoji: '😔', 
    color: 'from-slate-400 to-slate-600',
    label: 'Lonely'
  },
  creative: { 
    emoji: '🎨', 
    color: 'from-violet-400 to-purple-500',
    label: 'Creative'
  },
  determined: { 
    emoji: '💪', 
    color: 'from-orange-400 to-red-500',
    label: 'Determined'
  },
  loved: {
    emoji: '💕',
    color: 'from-pink-400 to-rose-500',
    label: 'Loved'
  },
  inspired: {
    emoji: '✨',
    color: 'from-yellow-300 to-amber-400',
    label: 'Inspired'
  },
  nostalgic: {
    emoji: '🌙',
    color: 'from-indigo-300 to-blue-400',
    label: 'Nostalgic'
  },
};

export const SAMPLE_CIRCLES = [
  {
    id: '1',
    name: 'Grief Circle',
    description: 'A safe space for processing loss and finding support through shared experiences.',
    bannerImage: 'https://images.pexels.com/photos/1420709/pexels-photo-1420709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 1247,
    entryCount: 8392,
    rules: ['Be respectful and supportive', 'No judgment zone', 'Share only what feels comfortable'],
    soulScore: 94,
    createdAt: Date.now() - 86400000 * 30,
    creator: '0x1234...5678',
    tags: ['grief', 'loss', 'healing', 'support'],
    isPrivate: false,
  },
  {
    id: '2',
    name: 'Love Letters',
    description: 'Express gratitude, love, and appreciation for people, moments, and experiences.',
    bannerImage: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 3241,
    entryCount: 15678,
    rules: ['Spread positivity', 'Celebrate love in all forms', 'No negativity'],
    soulScore: 98,
    createdAt: Date.now() - 86400000 * 60,
    creator: '0x2345...6789',
    tags: ['love', 'gratitude', 'appreciation', 'positivity'],
    isPrivate: false,
  },
  {
    id: '3',
    name: 'Breakthroughs',
    description: 'Share moments of clarity, personal growth, and significant realizations.',
    bannerImage: 'https://images.pexels.com/photos/1509582/pexels-photo-1509582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 892,
    entryCount: 4521,
    rules: ['Celebrate growth', 'Share insights', 'Encourage others'],
    soulScore: 91,
    createdAt: Date.now() - 86400000 * 45,
    creator: '0x3456...7890',
    tags: ['growth', 'breakthrough', 'clarity', 'insight'],
    isPrivate: false,
  },
  {
    id: '4',
    name: 'Midnight Thoughts',
    description: 'For the deep, introspective moments that come in the quiet hours.',
    bannerImage: 'https://images.pexels.com/photos/1624438/pexels-photo-1624438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 2156,
    entryCount: 9834,
    rules: ['Deep thoughts welcome', 'No shallow content', 'Embrace vulnerability'],
    soulScore: 96,
    createdAt: Date.now() - 86400000 * 20,
    creator: '0x4567...8901',
    tags: ['introspection', 'deep-thoughts', 'vulnerability', 'reflection'],
    isPrivate: false,
  },
  {
    id: '5',
    name: 'Creative Souls',
    description: 'Where artistic expression meets emotional release through creative journaling.',
    bannerImage: 'https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 1876,
    entryCount: 7263,
    rules: ['Share creative expressions', 'Support artistic growth', 'No plagiarism'],
    soulScore: 89,
    createdAt: Date.now() - 86400000 * 35,
    creator: '0x5678...9012',
    tags: ['creativity', 'art', 'expression', 'inspiration'],
    isPrivate: false,
  },
  {
    id: '6',
    name: 'Anxiety Support',
    description: 'Understanding and managing anxiety together in a supportive environment.',
    bannerImage: 'https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    memberCount: 2847,
    entryCount: 12456,
    rules: ['No medical advice', 'Share coping strategies', 'Be patient and kind'],
    soulScore: 93,
    createdAt: Date.now() - 86400000 * 25,
    creator: '0x6789...0123',
    tags: ['anxiety', 'mental-health', 'coping', 'support'],
    isPrivate: false,
  },
];

// Extended sample entries for feed (20+ posts)
export const SAMPLE_ENTRIES = [
  {
    id: '1',
    content: 'Today I realized that healing isn\'t linear. Some days I feel like I\'m moving backward, but maybe that\'s just part of the journey. The waves of grief come and go, and I\'m learning to surf them rather than fight them.',
    mood: 'reflective' as const,
    emoji: '🌊',
    timestamp: Date.now() - 3600000,
    author: '0x1234...5678',
    isPrivate: false,
    circleId: '1',
    bgColor: 'from-slate-800 to-slate-900',
  },
  {
    id: '2',
    content: 'The way the morning light hits my coffee cup reminds me that there\'s beauty in the simplest moments. Gratitude doesn\'t have to be grand - it can be as small as steam rising from a warm drink.',
    mood: 'grateful' as const,
    emoji: '☕',
    timestamp: Date.now() - 7200000,
    author: '0x2345...6789',
    isPrivate: false,
    circleId: '2',
    bgColor: 'from-amber-800 to-orange-900',
  },
  {
    id: '3',
    content: 'I\'ve been carrying this weight for so long, I forgot what it felt like to breathe freely. Today, for the first time in months, I exhaled completely. Sometimes the breakthrough isn\'t dramatic - it\'s just a breath.',
    mood: 'hopeful' as const,
    emoji: '🌅',
    timestamp: Date.now() - 10800000,
    author: '0x3456...7890',
    isPrivate: false,
    circleId: '3',
    bgColor: 'from-pink-800 to-purple-900',
  },
  {
    id: '4',
    content: 'The silence between 2 AM and 3 AM holds secrets. Tonight it whispered truths I wasn\'t ready to hear during the day. In darkness, we find different versions of ourselves.',
    mood: 'reflective' as const,
    emoji: '🌙',
    timestamp: Date.now() - 14400000,
    author: '0x4567...8901',
    isPrivate: false,
    circleId: '4',
    bgColor: 'from-indigo-900 to-purple-900',
  },
  {
    id: '5',
    content: 'My canvas today was blank for hours. Then I realized the blankness was the art - the space before creation, the pause before the storm, the quiet before the symphony. Sometimes emptiness is fullness.',
    mood: 'creative' as const,
    emoji: '🎨',
    timestamp: Date.now() - 18000000,
    author: '0x5678...9012',
    isPrivate: false,
    circleId: '5',
    bgColor: 'from-violet-800 to-purple-900',
  },
  {
    id: '6',
    content: 'Anxiety feels like drowning in shallow water. Everyone around you can stand, but somehow you can\'t find your footing. Today I remembered that it\'s okay to ask for a hand up.',
    mood: 'anxious' as const,
    emoji: '🫂',
    timestamp: Date.now() - 21600000,
    author: '0x7890...1234',
    isPrivate: false,
    circleId: '6',
    bgColor: 'from-red-800 to-pink-900',
  },
  {
    id: '7',
    content: 'Found an old photo today and smiled instead of crying. Progress isn\'t always moving forward - sometimes it\'s changing how we look back.',
    mood: 'nostalgic' as const,
    emoji: '📸',
    timestamp: Date.now() - 25200000,
    author: '0x8901...2345',
    isPrivate: false,
    bgColor: 'from-blue-800 to-indigo-900',
  },
  {
    id: '8',
    content: 'Love isn\'t always butterflies and fireworks. Sometimes it\'s choosing to stay when everything feels ordinary. Sometimes it\'s finding magic in the mundane.',
    mood: 'loved' as const,
    emoji: '💕',
    timestamp: Date.now() - 28800000,
    author: '0x9012...3456',
    isPrivate: false,
    circleId: '2',
    bgColor: 'from-pink-800 to-rose-900',
  },
  {
    id: '9',
    content: 'Today I wrote a letter to my younger self. I told them that the pain they\'re feeling will become their superpower, that their sensitivity is a gift, not a weakness.',
    mood: 'inspired' as const,
    emoji: '✨',
    timestamp: Date.now() - 32400000,
    author: '0x0123...4567',
    isPrivate: false,
    bgColor: 'from-yellow-800 to-amber-900',
  },
  {
    id: '10',
    content: 'The rain today matches my mood perfectly. Sometimes we need the storm to appreciate the sunshine. Sometimes we need to feel everything to feel anything at all.',
    mood: 'sad' as const,
    emoji: '🌧️',
    timestamp: Date.now() - 36000000,
    author: '0x1357...2468',
    isPrivate: false,
    bgColor: 'from-gray-800 to-slate-900',
  },
  {
    id: '11',
    content: 'Meditation isn\'t about emptying your mind - it\'s about watching your thoughts like clouds passing through the sky. Today I watched anger drift by without grabbing onto it.',
    mood: 'peaceful' as const,
    emoji: '☁️',
    timestamp: Date.now() - 39600000,
    author: '0x2468...1357',
    isPrivate: false,
    bgColor: 'from-blue-800 to-cyan-900',
  },
  {
    id: '12',
    content: 'I used to think vulnerability was weakness. Now I know it\'s the birthplace of courage, creativity, and change. Today I chose to be seen.',
    mood: 'determined' as const,
    emoji: '💪',
    timestamp: Date.now() - 43200000,
    author: '0x3691...4815',
    isPrivate: false,
    bgColor: 'from-orange-800 to-red-900',
  },
  {
    id: '13',
    content: 'The mirror showed me someone I didn\'t recognize today. Not because I\'ve changed, but because I\'m finally seeing myself clearly. Self-acceptance is a daily practice.',
    mood: 'reflective' as const,
    emoji: '🪞',
    timestamp: Date.now() - 46800000,
    author: '0x4815...3691',
    isPrivate: false,
    bgColor: 'from-purple-800 to-indigo-900',
  },
  {
    id: '14',
    content: 'Loneliness taught me the difference between being alone and being lonely. Today I enjoyed my own company for the first time in years.',
    mood: 'peaceful' as const,
    emoji: '🌱',
    timestamp: Date.now() - 50400000,
    author: '0x5926...7384',
    isPrivate: false,
    bgColor: 'from-green-800 to-emerald-900',
  },
  {
    id: '15',
    content: 'My therapist asked me what I would tell a friend going through this. Suddenly I realized how cruel I am to myself and how gentle I am to others. Time to flip that script.',
    mood: 'hopeful' as const,
    emoji: '🌈',
    timestamp: Date.now() - 54000000,
    author: '0x7384...5926',
    isPrivate: false,
    bgColor: 'from-pink-800 to-purple-900',
  },
  {
    id: '16',
    content: 'Dancing alone in my kitchen at midnight. No audience, no judgment, just pure joy moving through my body. This is what freedom feels like.',
    mood: 'excited' as const,
    emoji: '💃',
    timestamp: Date.now() - 57600000,
    author: '0x8147...6295',
    isPrivate: false,
    bgColor: 'from-yellow-800 to-orange-900',
  },
  {
    id: '17',
    content: 'Forgiveness isn\'t about them - it\'s about freeing yourself from the prison of resentment. Today I chose peace over being right.',
    mood: 'peaceful' as const,
    emoji: '🕊️',
    timestamp: Date.now() - 61200000,
    author: '0x6295...8147',
    isPrivate: false,
    bgColor: 'from-blue-800 to-teal-900',
  },
  {
    id: '18',
    content: 'The book I\'m reading says that we are not our thoughts, we are the observer of our thoughts. Today I practiced being the sky, not the weather.',
    mood: 'inspired' as const,
    emoji: '📚',
    timestamp: Date.now() - 64800000,
    author: '0x9517...3846',
    isPrivate: false,
    bgColor: 'from-indigo-800 to-purple-900',
  },
  {
    id: '19',
    content: 'Gratitude practice day 30: Today I\'m grateful for my scars. They remind me that I survived, that I\'m stronger than I thought, that healing is possible.',
    mood: 'grateful' as const,
    emoji: '🙏',
    timestamp: Date.now() - 68400000,
    author: '0x3846...9517',
    isPrivate: false,
    bgColor: 'from-emerald-800 to-teal-900',
  },
  {
    id: '20',
    content: 'Sometimes the bravest thing you can do is rest. Today I chose to honor my exhaustion instead of pushing through it. Self-care is not selfish.',
    mood: 'peaceful' as const,
    emoji: '🛌',
    timestamp: Date.now() - 72000000,
    author: '0x1592...6374',
    isPrivate: false,
    bgColor: 'from-slate-800 to-gray-900',
  },
];

// Circle-specific entries (50+ per circle)
export const SAMPLE_CIRCLE_ENTRIES: Record<string, any[]> = {
  '1': [ // Grief Circle - 50 entries
    {
      id: 'grief_1',
      content: 'Today marks six months since you left. I thought I\'d be "better" by now, but grief doesn\'t follow calendars. I\'m learning that missing you isn\'t something to get over - it\'s something to carry with love.',
      mood: 'sad',
      emoji: '💙',
      timestamp: Date.now() - 3600000,
      author: '0x1111...1111',
      isPrivate: false,
      circleId: '1',
      bgColor: 'from-blue-800 to-indigo-900',
    },
    {
      id: 'grief_2',
      content: 'Grief is love with nowhere to go. Today I planted flowers in your memory and felt you in the wind that rustled the leaves. Love doesn\'t die when someone does.',
      mood: 'peaceful',
      emoji: '🌸',
      timestamp: Date.now() - 7200000,
      author: '0x2222...2222',
      isPrivate: false,
      circleId: '1',
      bgColor: 'from-pink-800 to-purple-900',
    },
    {
      id: 'grief_3',
      content: 'The hardest part isn\'t the big moments - it\'s the small ones. Wanting to text you about something funny, reaching for the phone to call you, setting two plates instead of one.',
      mood: 'lonely',
      emoji: '📱',
      timestamp: Date.now() - 10800000,
      author: '0x3333...3333',
      isPrivate: false,
      circleId: '1',
      bgColor: 'from-gray-800 to-slate-900',
    },
    // Add 47 more grief entries...
    {
      id: 'grief_50',
      content: 'One year later, and I\'m finally understanding that grief isn\'t something you "get through" - it\'s something you grow around. You become bigger than your pain, but the pain remains.',
      mood: 'reflective',
      emoji: '🌳',
      timestamp: Date.now() - 180000000,
      author: '0x5050...5050',
      isPrivate: false,
      circleId: '1',
      bgColor: 'from-green-800 to-emerald-900',
    },
  ],
  '2': [ // Love Letters - 50 entries
    {
      id: 'love_1',
      content: 'To the stranger who smiled at me in the grocery store today: you have no idea how much I needed that small act of kindness. Thank you for reminding me that goodness exists everywhere.',
      mood: 'grateful',
      emoji: '😊',
      timestamp: Date.now() - 3600000,
      author: '0x3333...3333',
      isPrivate: false,
      circleId: '2',
      bgColor: 'from-yellow-800 to-orange-900',
    },
    {
      id: 'love_2',
      content: 'Dear morning coffee, you are my daily meditation, my moment of peace before the world wakes up. Thank you for being consistently perfect in an inconsistent world.',
      mood: 'peaceful',
      emoji: '☕',
      timestamp: Date.now() - 7200000,
      author: '0x4444...4444',
      isPrivate: false,
      circleId: '2',
      bgColor: 'from-amber-800 to-brown-900',
    },
    // Add 48 more love entries...
  ],
  // Add entries for circles 3, 4, 5, 6 with 50 entries each...
};

export const CONTRACT_ADDRESSES = {
  SOUL_ENTRY: process.env.NEXT_PUBLIC_SOUL_ENTRY_CONTRACT || '0x1234567890123456789012345678901234567890',
  SOUL_CIRCLE: process.env.NEXT_PUBLIC_SOUL_CIRCLE_CONTRACT || '0x2345678901234567890123456789012345678901',
  SOUL_TOKEN: process.env.NEXT_PUBLIC_SOUL_TOKEN_CONTRACT || '0x3456789012345678901234567890123456789012',
};